apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-rest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-rest-app
  template:
    metadata:
      labels:
        app: spring-rest-app
    spec:
      containers:
        - name: springboot
          image: mohanduanil/hackathonrepo:spring-rest-app
          ports:
            - containerPort: 8080   # Container Running 
---
apiVersion: v1
kind: Service
metadata:
  name: spring-rest-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080  # service running port in cluster
      targetPort: 8080  # service exposed port
  selector:
    app: spring-rest-app
